#!/bin/sh
# Builds app.js from src/*.js and stamps cache-busting hashes into index.html.
# app.js is generated — never edit it. Edit src/*.js and re-run this.
set -eu
cd "$(dirname "$0")"

ORDER='core logos shots players roster seeds bracket awards share'

# logos.js is generated from the logos/ directory: drop a <key>.webp in and
# rebuild. A team with no file gets the designed mark instead, so the set can
# be completed a few at a time without anything looking broken in between.
{
  echo "/* Generated by build.sh from logos/. Do not hand-edit. */"
  printf 'const LOGOS={'
  first=1
  for f in logos/*; do
    [ -e "$f" ] || continue
    b=$(basename "$f"); k=${b%.*}; e=${b##*.}
    [ $first -eq 1 ] || printf ','
    printf "%s:'%s'" "$k" "$e"
    first=0
  done
  echo '};'
} > src/logos.js

# shots.js the same way, from headshots/. A player without a file falls back to
# his initials on the team's colour, so the set can be completed piecemeal.
{
  echo "/* Generated by build.sh from headshots/. Do not hand-edit. */"
  printf 'const SHOTS=new Set(['
  first=1
  for f in headshots/*.webp; do
    [ -e "$f" ] || continue
    k=$(basename "$f" .webp)
    [ $first -eq 1 ] || printf ','
    printf "'%s'" "$k"
    first=0
  done
  echo ']);'
} > src/shots.js

missing=''
for f in src/*.js; do
  b=$(basename "$f" .js)
  case " $ORDER " in *" $b "*) ;; *) missing="$missing $b" ;; esac
done
[ -z "$missing" ] || { echo "build: src file(s) not in ORDER:$missing" >&2; exit 1; }

{
  echo "/* NFL Predictions — built from src/*.js; edit those and re-run build.sh */"
  for b in $ORDER; do
    [ -f "src/$b.js" ] || { echo "build: missing src/$b.js" >&2; exit 1; }
    echo; echo "/* ===== $b.js ===== */"
    cat "src/$b.js"
  done
  echo; echo "boot();"
} > app.js.tmp
mv app.js.tmp app.js

hash() { if command -v shasum >/dev/null 2>&1; then shasum "$1"; else sha1sum "$1"; fi | cut -c1-12; }
CSSV=$(hash style.css); JSV=$(hash app.js)
sed -e "s|style\.css?v=[^\"]*|style.css?v=$CSSV|" -e "s|app\.js?v=[^\"]*|app.js?v=$JSV|" \
  index.html > index.html.tmp && mv index.html.tmp index.html

# A CSS animation naming a keyframe that does not exist is ignored silently.
if command -v python3 >/dev/null 2>&1; then
python3 - style.css <<'PYEOF'
import re,sys
css=re.sub(r'/\*.*?\*/','',open(sys.argv[1]).read(),flags=re.S)
d={m.group(1) for m in re.finditer(r'@keyframes\s+([A-Za-z_-][\w-]*)',css)}
KW={'none','ease','linear','ease-in','ease-out','ease-in-out','infinite','forwards',
    'backwards','both','normal','reverse','alternate','running','paused'}
bad=[]
for m in re.finditer(r'animation(?:-name)?\s*:\s*([^;{}]+)',css):
    for t in re.split(r'[,\s]+',re.sub(r'[A-Za-z-]+\([^()]*\)',' ',m.group(1))):
        t=t.strip()
        if t and t not in KW and not re.fullmatch(r'-?[\d.]+(m?s)?',t) \
           and re.fullmatch(r'[A-Za-z_-][\w-]*',t) and t not in d: bad.append(t)
if bad:
    sys.stderr.write('build: missing @keyframes: %s\n'%', '.join(sorted(set(bad))));sys.exit(1)
PYEOF
fi

if command -v node >/dev/null 2>&1; then
  node --check app.js || { echo "build: SYNTAX ERROR in app.js" >&2; exit 1; }
fi
echo "build: app.js $(wc -c < app.js | tr -d ' ') bytes  style.css?v=$CSSV  app.js?v=$JSV"
