#!/usr/bin/env python3
"""Generate src/roster.js from rosters-2026.csv.

The board is the curated, priced shortlist. This is everyone else — the people
you can still find in the search box even though the market never priced them.
Linemen, kickers, punters and long snappers are dropped: no award here has ever
gone to one, so they would only ever be in the way.

    python3 tools/roster.py && ./build.sh
"""
import csv, os, re, sys

DROP = {'C','G','OT','OL','LS','P','PK'}
# the board calls edge rushers EDGE; the roster calls them DE. One label in one
# list, so they match rather than sitting next to each other spelled differently.
MAP  = {'DE':'EDGE','DL':'DT'}
# the sheet spells Washington WSH; everything else in this app says WAS, and a
# code the app does not know draws no logo and no colour.
TEAM = {'WSH':'WAS'}

here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = list(csv.DictReader(open(os.path.join(here,'rosters-2026.csv'))))

out, seen = [], set()
for r in rows:
    pos = r['Position'].strip()
    if pos in DROP: continue
    unit = 'O' if r['Unit'].strip()=='Offense' else 'D'
    name = r['Player'].strip()
    team = TEAM.get(r['Team'].strip(), r['Team'].strip())
    if not name or not team: continue
    k = (name.lower(), team)
    if k in seen: continue
    seen.add(k)
    out.append((name, team, MAP.get(pos,pos), unit))

out.sort(key=lambda x:(x[0].split()[-1], x[0]))
esc = lambda s: s.replace('\\','\\\\').replace("'","\\'")
cells = [f"['{esc(n)}','{t}','{p}','{u}']" for n,t,p,u in out]
lines = [' '+','.join(cells[i:i+3]) for i in range(0,len(cells),3)]

open(os.path.join(here,'src','roster.js'),'w').write(
 "/* Generated by tools/roster.py from rosters-2026.csv. Do not hand-edit.\n"
 f"   {len(out)} players — every skill position on all 32 rosters. Linemen,\n"
 "   kickers, punters and long snappers are left out. The fourth field is the\n"
 "   side of the ball, which is what keeps offensive names out of the defensive\n"
 "   award's search and the other way round. */\n"
 "const ROSTER=[\n" + ",\n".join(lines) + "];\n"
 "const rosterFor=side=>ROSTER.filter(r=>!side||r[3]===side)\n"
 " .map(([n,t,p])=>({n,t,p,o:''}));\n")
print(f"roster.js: {len(out)} players "
      f"({sum(1 for r in out if r[3]=='O')} offense, {sum(1 for r in out if r[3]=='D')} defense)")
